### ISSUE TITLE
 Could not enable torch

### ISSUE THREAD

**Issue by Dr0sophila** [svprdga/torch_light#17]
``E/flutter (15478): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [EnableTorchException: Could not enable torch: java.lang.IllegalArgumentException: Bad argument passed to camera service]
E/flutter (15478): #0      TorchLight.enableTorch (package:torch_light/torch_light.dart:56:11)
E/flutter (15478): <asynchronous suspension>
E/flutter (15478): 
E/flutter (15478): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [EnableTorchException: Could not enable torch: java.lang.IllegalArgumentException: Bad argument passed to camera service]
E/flutter (15478): #0      TorchLight.enableTorch (package:torch_light/torch_light.dart:56:11)
E/flutter (15478): <asynchronous suspension>
E/flutter (15478): 
``

**Comment by svprdga** [comment]
Hi, thank you for reporting this bug. Please edit your message with the following information:

- What were you doing when the error occurred
- What did you expect to happen
- Device details (brand, model, Android version or iOS version)
- The output of running `flutter doctor -v`
- Ideally, a code snippet or project in which I can reproduce this error

Thanks.

**Comment by Dr0sophila** [comment]
The flash can't be open.
EnableTorchException: Could not enable torch: java.lang.IllegalArgumentException: Bad argument passed to camera service


this is my code

```dart
// ignore_for_file: file_names

import 'package:flutter/material.dart';
import 'package:torch_light/torch_light.dart';
import 'dart:async';

class light extends StatefulWidget {
  @override
  _lightState createState() => _lightState();
}

class _lightState extends State<light> {
  bool _hasFlash = false;
  bool _isOn = false;
  double _intensity = 1.0;

  @override
  initState() {
    super.initState();
    initPlatformState();
  }

  initPlatformState() async {
    bool hasFlash = await TorchLight.isTorchAvailable();
    print("Device has flash ? $hasFlash");
    setState(() {
      _hasFlash = hasFlash;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          backgroundColor: const Color.fromRGBO(211, 192, 64, 1),
          leading: MaterialButton(
            onPressed: () {
              Navigator.pop(context);
            },
            child: const Icon(
              Icons.arrow_back_ios,
              color: Colors.white,
            ),
          ),
          centerTitle: true,
          elevation: 2.0,
          title: const Text(
            "手电筒",
            style: TextStyle(
              fontWeight: FontWeight.w900,
              color: Colors.white,
              fontSize: 25.0,
            ),
          ),
        ),
        body: Center(
          child: MaterialButton(
            onPressed: _turnFlash,
            child: Image(
              width: MediaQuery.of(context).size.width,
              image: AssetImage(
                  "assets/img/${_isOn ? "flash_off" : "flash_on"}.png"),
            ),
          ),
        ));
  }

  Future _turnFlash() async {
    TorchLight.enableTorch();
    _isOn ? TorchLight.disableTorch() : TorchLight.enableTorch();
    var f = await TorchLight.isTorchAvailable();
    setState(() {
      _hasFlash = f;
      _isOn = !_isOn;
    });
  }
}

```

the flutter version as follows:
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19045.2251], locale zh-CN)
    • Flutter version 2.5.3 at D:\downloads\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (1 year, 1 month ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\psy\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: D:\downloads\Android_Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.3)
    • Android Studio at D:\downloads\Android_Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\psy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 107.0.5304.107
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 107.0.1418.56

the error info:
E/flutter (15478): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [EnableTorchException: Could not enable torch: java.lang.IllegalArgumentException: Bad argument passed to camera service] E/flutter (15478): #0 TorchLight.enableTorch (package:torch_light/torch_light.dart:56:11) E/flutter (15478): <asynchronous suspension> E/flutter (15478): E/flutter (15478): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [EnableTorchException: Could not enable torch: java.lang.IllegalArgumentException: Bad argument passed to camera service] E/flutter (15478): #0 TorchLight.enableTorch (package:torch_light/torch_light.dart:56:11) E/flutter (15478): <asynchronous suspension> E/flutter (15478):

**Comment by svprdga** [comment]
Are you running this on an Android emulator?

**Comment by Dr0sophila** [comment]
no,and the camera can be found.

**Comment by magical-psy** [comment]
the permission I set
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.FLASHLIGHT" />
<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.camera.autofocus" />
<uses-feature android:name="android.hardware.camera.flash" />

this is my device: Redmi Note 4X

**Comment by Dr0sophila** [comment]
I tried another device:Redmi Note 8 Pro ,the code works successfully,but it won't run on Redmi Note 4X.

**Comment by svprdga** [comment]
Could you extract the logcat output of the error?
